### ISSUE TITLE
Retour Job4

### ISSUE THREAD

**Issue by cchanche** [Julien-epi/test-job4#1]
Bonjour Julien,

Merci pour ton temps sur ce projet, malheureusement il va être en dessous de nos attentes pour le poste.

Ton application est prometteuse : tu as bien saisi l'enjeu du sujet, ton application frontend s'interface correctement avec ton backend, et tu as même réussi à implanter les services du sujet concernant le _user_.

Malgré ton manque d'experience en NestJS, tu as sû explorer les différentes documentations pour mettre en place une API fonctionnelle. 

Nous reconnaissons aussi ton effort de vouloir implanter une entité supplémentaire et ses services, les relations font en effet partie des connaissances essentielles à maîtriser pour travailler sur ce genre de projet.

Cependant, les _address_ ne faisaient pas partie du sujet, et nous aurions aimé que tu passes plus de temps sur la qualité de code et les outils de développement. Dans un soucis de transparence, et aussi pour que tu puisses capitaliser sur ce test, voici, dans l'ordre de priorité, les ressources à explorer qui pourraient t'aider :

1. **Commits et branches git** : 
  - Itérer plus fréquemment en faisant des commits
  - Utiliser des branches : voir le [_GitFlow_](https://datasift.github.io/gitflow/IntroducingGitFlow.html)
  - Ecrire des messages de commits : voir _convention de commits_ (ex: [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary))
2. **Commentaires** : 
  - La documentation ne s'arrête pas au README, il faut aussi écrire fréquemment des commentaires dans ton code tel qu'il soit lisible par n'importe-qui. Voir [_How to write good comments_](https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/)
  - Ne pas laisser de code commenté ou de code inutilisé (ex: `address.service.ts`)
3. **Environnement de développement**. Même si tu as été et sera le seul à développer sur ce projet _demo_, nous aurions aimé y retrouver des outils qui facilitent le développement et la qualité de code :
  - Formatage de code : permet d'assurer que tous les développeurs produisent un code qui implémente les mêmes conventions d'écriture (tabulations, espaces, virgules etc...). Voir [_Prettier_](https://prettier.io/)
  - _Linter_ : a travers une collection de règles, détecte le code qui ne convient pas à la convention configurée. (ex: `no-unsued-var` lève une erreur si une variable est déclarée/importée, mais pas utilisée. `front/src/services/authServices.ts:24:2` : _'User' is defined but never used._). Voir [_eslint_](https://eslint.org/)
  - Une meilleure configuration de tes `package.json`
    - Dans `front/package.json`, tu as inclus les déclarations de type dans les dépendances de production (ex: `@types/node`).
    - Spécifie aussi la version de [_node_](https://nodejs.org/en/) à utiliser. Voir [npm docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines).
  - Choisis un package-manager : dans le frontend, tu as commit à la fois `yarn.lock` et `package-lock.json`. Ces fichiers doivent être inclus dans le système de versionnage puisqu'ils assurent la stabilité et la cohérence des dépendances, cependant, leur syntaxe dépend du _package manager_ que tu utilise, et en inclure deux introduit de l'incohérence et de l'instabilité vis-à-vis des dépendances résolues. Tu es familier avec [_npm_](https://www.npmjs.com/package/npm) et probablement [_yarn_](https://www.npmjs.com/package/yarn), mais il existe aussi _pnpm_, _yarn@v2_, etc... Le plus souvent, les développeurs savent quel package-manager utiliser grâce au _lockfile_ : 
    - `pnpm-lock.yaml` -> pnpm
    - `yarn.lock` -> yarn
    - `package-lock.json` -> npm
    - Tu peux aussi utiliser [le champ `engines`](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines) de ton `package.json`
4. **Configuration base de données** : 
  - Pour lancer et utiliser ton projet correctement, nous avons eu à configurer et lancer une base de données locale par nos propres moyens. Un article de documentation pour la marche à suivre aurait été le bienvenu, mais la convention pour l'utilisation d'une db en _local_ (pour le développement) est d'utiliser [_Docker_](https://www.docker.com/) avec [`$ docker-compose`](https://docs.docker.com/compose/). (et en plus, c'est francais ! :fr: :wink:). Par exemple, pour le projet, la configuration suivant aurait suffit : 

```yml
# back/docker-compose.yml
version: "3.4"

services:
  database:
    # In production, you may want to use a managed database service
    container_name: database
    image: postgres
    environment:
      - POSTGRES_DB=test-job4
      - POSTGRES_USER=postgres
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=root
    volumes:
      # Bind the docker volume 'db-data' to the container
      - db-data:/var/lib/postgresql/data:rw
    ports:
      # Binds user-defined port to default mongo's 27017
      - "5432:5432"

volumes:
  # Creates a db-data docker volume.
  # Clear the volume with `docker volume prune`
  db-data:
```

Pour finir, nous aurions aimé connaître ton ressenti quant-à la contrainte de temps. Comment cette dernière as-t-elle changé la manière dont tu as priorisé tes tâches ? Aurais-tu aimée disposer de plus de temps ? Qu'aurais-tu priorisé si tu avais eu deux jours de plus ?

Merci, encore une fois, pour ta coopération.
Nous te souhaitons bon courage dans tes recherches,
_L'équipe tech_.
